fix: multiple occurrences with --upstream
We need to add `multiple_occurrences = true` to `CmdOptions.upstream` to make sure
we can use `balancebeam` with `-u addr:port -u addr:port`, and pass the `test_load_distribution`.
Otherwise, it will occur this error:
```
error: The argument '--upstream <UPSTREAM>...' was provided more than once, but cannot be used multiple times
```